name: ionicons
description: Ionicons v5.3.0 for Flutter
version: 0.1.0
homepage: https://github.com/ez-connect/flutter-ionicons

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Ionicons
      fonts:
        - asset: fonts/Ionicons.ttf
